### ISSUE TITLE
Add support for configuration of the guacamole tunnel protocol for utility endpoints

### ISSUE THREAD

**Issue by olberger** [nre-learning/syringe#110]
Currently, utility endpoints are displayed using Guacamole's SSH terminal interface, connecting to guacd with a "ssh" protocol on the service's IP and port 22.

In order to make Antidote support VNC too (or RDP or telnet) as per https://github.com/nre-learning/antidote-web/issues/65 it would be great to add some elements of configuration of the Guacamole protocol to use for each utility.

Antidote basically supports VNC currently, and just needs the protocol and port to be provided to the antidote.js so that it can create the right kind of tunnel, and Syring should tell it which protocol to choose depending on the confugation chosen by lab authors.

Note that we may envision multiple connections to a single pod utility simultaneaouly, in different tabs, for instance through SSH and VNC in 2 parallel tabs (i.e. 2 Guacamole tunnels), so, like for ports, this should be a list of protocols and not a single enum.

**Comment by olberger** [comment]
Oh, and I'm not really yet able to hack in go to propose an implementation... I've been able to do JS, Java and test a PoC, but if a nice go hacker would like to help, I'd be forever grateful ;)

**Comment by olberger** [comment]
Oh, and Syringe would also have to pass the size of the canvas to the VNC-equipped utility pod/container so that it startx the X display with the same size...

**Comment by Mierdin** [comment]
Sorry for the huge delay on this issue, but it seems this isn't necessary anymore. The new presentations abstraction in v0.4.0 opens the door to make the introduction of VNC much easier. Beyond specifying a presentation type of `vnc`, you shouldn't need to do any more on the lesson definition side of things - Syringe will pass the IP:PORT to antidote-web, just like it does with SSH today. Obviously VNC support is still forthcoming, but I am not sure the original intent for this issue is relevant anymore - Syringe doesn't care too much about guac tunnel settings even today with SSH.

Okay to close, or did I miss something?

**Comment by Mierdin** [comment]
I'm going to assume this is good to close, not only because of the above but because we'll be moving away from Guacamole.
